default_agent: l27agentcore_Agent
agents:
  l27agentcore_Agent:
    name: l27agentcore_Agent
    entrypoint: 10_production/l27agentcore/src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: 10_production/l27agentcore/src
    aws:
      execution_role: null
      execution_role_auto_create: false
      account: <data-account-id>
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: l27agentcore_Agent-8SQjr5BSN3
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:<data-account-id>:runtime/l27agentcore_Agent-8SQjr5BSN3
      agent_session_id: 19052f41-1dc8-40ef-aac0-1bef71149f7b
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
